INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-001', 'KIMCHI', 100, 1500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-002', 'POTATO', 10, 2300);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-003', 'COLA', 25, 1700);