INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-001', 'KIMCHI', 100, 1700);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-002', 'POTATO', 300, 1700);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-003', 'COLA', 400, 1700);